// Generated from the Feishu Bitable material CMS.
// Do not edit by hand; run scripts/sync-material-cms.mjs.

export const MATERIAL_CMS_ITEMS = {
  "mat-sticker-gwqu9k": {
    "id": "mat-sticker-gwqu9k",
    "title": "猫嘴",
    "type": "sticker",
    "group": "face-cover",
    "status": "上架",
    "sortOrder": 1,
    "author": "小天使",
    "sourceKey": "sticker:user:face-cover-lace-heart.png",
    "packId": "face-cover",
    "src": "./assets/user_stickers/face-cover-lace-heart.png",
    "previewSrc": "./assets/sticker_previews/user/face-cover-lace-heart.png"
  },
  "mat-sticker-1cnwf3b": {
    "id": "mat-sticker-1cnwf3b",
    "title": "GAME OVER",
    "type": "sticker",
    "group": "face-cover",
    "status": "上架",
    "sortOrder": 2,
    "author": "小天使",
    "sourceKey": "sticker:user:sel_01.png",
    "packId": "face-cover",
    "src": "./assets/user_stickers/sel_01.png",
    "previewSrc": "./assets/sticker_previews/user/sel_01.png"
  },
  "mat-sticker-gf9szz": {
    "id": "mat-sticker-gf9szz",
    "title": "secret",
    "type": "sticker",
    "group": "face-cover",
    "status": "上架",
    "sortOrder": 3,
    "author": "小天使",
    "sourceKey": "sticker:user:sel_03.png",
    "packId": "face-cover",
    "src": "./assets/user_stickers/sel_03.png",
    "previewSrc": "./assets/sticker_previews/user/sel_03.png"
  },
  "mat-sticker-qd1dyv": {
    "id": "mat-sticker-qd1dyv",
    "title": "secret",
    "type": "sticker",
    "group": "face-cover",
    "status": "上架",
    "sortOrder": 4,
    "author": "小天使",
    "packId": "face-cover",
    "src": "./assets/user_stickers/split-11.png",
    "previewSrc": "./assets/sticker_previews/user/split-11.png"
  },
  "mat-sticker-x8gqke": {
    "id": "mat-sticker-x8gqke",
    "title": "secret",
    "type": "sticker",
    "group": "face-cover",
    "status": "上架",
    "sortOrder": 5,
    "author": "小天使",
    "packId": "face-cover",
    "src": "./assets/user_stickers/split-10.png",
    "previewSrc": "./assets/sticker_previews/user/split-10.png"
  },
  "mat-sticker-um0rkm": {
    "id": "mat-sticker-um0rkm",
    "title": "thank you",
    "type": "sticker",
    "group": "face-cover",
    "status": "上架",
    "sortOrder": 6,
    "author": "小天使",
    "packId": "face-cover",
    "src": "./assets/user_stickers/split-18.png",
    "previewSrc": "./assets/sticker_previews/user/split-18.png"
  },
  "mat-sticker-b8559p": {
    "id": "mat-sticker-b8559p",
    "title": "模糊爱心",
    "type": "sticker",
    "group": "face-cover",
    "status": "上架",
    "sortOrder": 7,
    "author": "小天使",
    "packId": "face-cover",
    "src": "./assets/user_stickers/split-19.png",
    "previewSrc": "./assets/sticker_previews/user/split-19.png"
  },
  "mat-sticker-n7nvpi": {
    "id": "mat-sticker-n7nvpi",
    "title": "みせないよ！",
    "type": "sticker",
    "group": "face-cover",
    "status": "上架",
    "sortOrder": 8,
    "author": "小天使",
    "packId": "face-cover",
    "src": "./assets/user_stickers/微信图片_20260702014117_517_13.png",
    "previewSrc": "./assets/sticker_previews/user/微信图片_20260702014117_517_13.png"
  },
  "mat-sticker-10pslce": {
    "id": "mat-sticker-10pslce",
    "title": "みせないよ！",
    "type": "sticker",
    "group": "face-cover",
    "status": "上架",
    "sortOrder": 9,
    "author": "小天使",
    "packId": "face-cover",
    "src": "./assets/user_stickers/微信图片_20260702014116_516_13.png",
    "previewSrc": "./assets/sticker_previews/user/微信图片_20260702014116_516_13.png"
  },
  "mat-sticker-1u4s0ms": {
    "id": "mat-sticker-1u4s0ms",
    "title": "きらい",
    "type": "sticker",
    "group": "face-cover",
    "status": "上架",
    "sortOrder": 4,
    "author": "小天使",
    "sourceKey": "sticker:user:sel_08.png",
    "packId": "face-cover",
    "src": "./assets/user_stickers/sel_08.png",
    "previewSrc": "./assets/sticker_previews/user/sel_08.png"
  },
  "mat-sticker-m1cqxp": {
    "id": "mat-sticker-m1cqxp",
    "title": "天使光环",
    "type": "sticker",
    "group": "face-cover",
    "status": "上架",
    "sortOrder": 5,
    "author": "小天使",
    "sourceKey": "sticker:user:sel_09.png",
    "packId": "face-cover",
    "src": "./assets/user_stickers/sel_09.png",
    "previewSrc": "./assets/sticker_previews/user/sel_09.png"
  },
  "mat-sticker-1n3urnj": {
    "id": "mat-sticker-1n3urnj",
    "title": "XXX",
    "type": "sticker",
    "group": "face-cover",
    "status": "上架",
    "sortOrder": 6,
    "author": "小天使",
    "sourceKey": "sticker:user:sel_12.png",
    "packId": "face-cover",
    "src": "./assets/user_stickers/sel_12.png",
    "previewSrc": "./assets/sticker_previews/user/sel_12.png"
  },
  "mat-sticker-1yeg2sp": {
    "id": "mat-sticker-1yeg2sp",
    "title": "爱心点赞",
    "type": "sticker",
    "group": "face-cover",
    "status": "上架",
    "sortOrder": 7,
    "author": "小天使",
    "sourceKey": "sticker:user:sel_13.png",
    "packId": "face-cover",
    "src": "./assets/user_stickers/sel_13.png",
    "previewSrc": "./assets/sticker_previews/user/sel_13.png"
  },
  "mat-sticker-1j4bpwg": {
    "id": "mat-sticker-1j4bpwg",
    "title": "みせないよ！",
    "type": "sticker",
    "group": "face-cover",
    "status": "上架",
    "sortOrder": 8,
    "author": "小天使",
    "sourceKey": "sticker:user:deco_02.png",
    "packId": "face-cover",
    "src": "./assets/user_stickers/deco_02.png",
    "previewSrc": "./assets/sticker_previews/user/deco_02.png"
  },
  "mat-sticker-1j2l3qc": {
    "id": "mat-sticker-1j2l3qc",
    "title": "爱心十字架",
    "type": "sticker",
    "group": "face-cover",
    "status": "上架",
    "sortOrder": 9,
    "author": "小天使",
    "sourceKey": "sticker:user:deco_08.png",
    "packId": "face-cover",
    "src": "./assets/user_stickers/deco_08.png",
    "previewSrc": "./assets/sticker_previews/user/deco_08.png"
  },
  "mat-sticker-dvogph": {
    "id": "mat-sticker-dvogph",
    "title": "すき气泡",
    "type": "sticker",
    "group": "face-cover",
    "status": "上架",
    "sortOrder": 10,
    "author": "小天使",
    "sourceKey": "sticker:user:sel_05.png",
    "packId": "face-cover",
    "src": "./assets/user_stickers/sel_05.png",
    "previewSrc": "./assets/sticker_previews/user/sel_05.png"
  },
  "mat-sticker-12ze4kk": {
    "id": "mat-sticker-12ze4kk",
    "title": "爱心气泡",
    "type": "sticker",
    "group": "face-cover",
    "status": "上架",
    "sortOrder": 11,
    "author": "小天使",
    "sourceKey": "sticker:user:sel_06.png",
    "packId": "face-cover",
    "src": "./assets/user_stickers/sel_06.png",
    "previewSrc": "./assets/sticker_previews/user/sel_06.png"
  },
  "mat-sticker-j0br8f": {
    "id": "mat-sticker-j0br8f",
    "title": "爱心死",
    "type": "sticker",
    "group": "face-cover",
    "status": "暂不上架",
    "sortOrder": 12,
    "author": "小天使",
    "sourceKey": "sticker:user:sel_04.png",
    "packId": "face-cover",
    "src": "./assets/user_stickers/sel_04.png",
    "previewSrc": "./assets/sticker_previews/user/sel_04.png"
  },
  "mat-sticker-15celbn": {
    "id": "mat-sticker-15celbn",
    "title": "が",
    "type": "sticker",
    "group": "face-cover",
    "status": "上架",
    "sortOrder": 13,
    "author": "小天使",
    "sourceKey": "sticker:user:sel_07.png",
    "packId": "face-cover",
    "src": "./assets/user_stickers/sel_07.png",
    "previewSrc": "./assets/sticker_previews/user/sel_07.png"
  },
  "mat-sticker-1cijra7": {
    "id": "mat-sticker-1cijra7",
    "title": "I HATE U",
    "type": "sticker",
    "group": "face-cover",
    "status": "上架",
    "sortOrder": 14,
    "author": "小天使",
    "sourceKey": "sticker:user:sel_10.png",
    "packId": "face-cover",
    "src": "./assets/user_stickers/sel_10.png",
    "previewSrc": "./assets/sticker_previews/user/sel_10.png"
  },
  "mat-sticker-13ejray": {
    "id": "mat-sticker-13ejray",
    "title": "secret",
    "type": "sticker",
    "group": "face-cover",
    "status": "上架",
    "sortOrder": 15,
    "author": "小天使",
    "sourceKey": "sticker:user:sel_11.png",
    "packId": "face-cover",
    "src": "./assets/user_stickers/sel_11.png",
    "previewSrc": "./assets/sticker_previews/user/sel_11.png"
  },
  "mat-sticker-ju85ky": {
    "id": "mat-sticker-ju85ky",
    "title": "みせないよ！",
    "type": "sticker",
    "group": "face-cover",
    "status": "上架",
    "sortOrder": 16,
    "author": "小天使",
    "sourceKey": "sticker:user:deco_01.png",
    "packId": "face-cover",
    "src": "./assets/user_stickers/deco_01.png",
    "previewSrc": "./assets/sticker_previews/user/deco_01.png"
  },
  "mat-sticker-1fdtsa3": {
    "id": "mat-sticker-1fdtsa3",
    "title": "爱心十字架",
    "type": "sticker",
    "group": "face-cover",
    "status": "上架",
    "sortOrder": 17,
    "author": "小天使",
    "sourceKey": "sticker:user:deco_03.png",
    "packId": "face-cover",
    "src": "./assets/user_stickers/deco_03.png",
    "previewSrc": "./assets/sticker_previews/user/deco_03.png"
  },
  "mat-sticker-kc9rug": {
    "id": "mat-sticker-kc9rug",
    "title": "爱心绑带",
    "type": "sticker",
    "group": "face-cover",
    "status": "上架",
    "sortOrder": 18,
    "author": "小天使",
    "sourceKey": "sticker:user:deco_04.png",
    "packId": "face-cover",
    "src": "./assets/user_stickers/deco_04.png",
    "previewSrc": "./assets/sticker_previews/user/deco_04.png"
  },
  "mat-sticker-1uibli7": {
    "id": "mat-sticker-1uibli7",
    "title": "爱心十字架",
    "type": "sticker",
    "group": "face-cover",
    "status": "上架",
    "sortOrder": 19,
    "author": "小天使",
    "sourceKey": "sticker:user:deco_05.png",
    "packId": "face-cover",
    "src": "./assets/user_stickers/deco_05.png",
    "previewSrc": "./assets/sticker_previews/user/deco_05.png"
  },
  "mat-sticker-1w15n12": {
    "id": "mat-sticker-1w15n12",
    "title": "爱心十字架",
    "type": "sticker",
    "group": "face-cover",
    "status": "上架",
    "sortOrder": 20,
    "author": "小天使",
    "sourceKey": "sticker:user:deco_06.png",
    "packId": "face-cover",
    "src": "./assets/user_stickers/deco_06.png",
    "previewSrc": "./assets/sticker_previews/user/deco_06.png"
  },
  "mat-sticker-1pi01ui": {
    "id": "mat-sticker-1pi01ui",
    "title": "爱心十字架",
    "type": "sticker",
    "group": "face-cover",
    "status": "上架",
    "sortOrder": 21,
    "author": "小天使",
    "sourceKey": "sticker:user:deco_07.png",
    "packId": "face-cover",
    "src": "./assets/user_stickers/deco_07.png",
    "previewSrc": "./assets/sticker_previews/user/deco_07.png"
  },
  "mat-sticker-j5uuvp": {
    "id": "mat-sticker-j5uuvp",
    "title": "粉色线框",
    "type": "sticker",
    "group": "hand-drawn",
    "status": "上架",
    "sortOrder": 22,
    "author": "小天使",
    "sourceKey": "sticker:hand-drawn:hand-drawn-01.png",
    "packId": "hand-drawn",
    "src": "./assets/user_stickers/hand-drawn-01.png",
    "previewSrc": "./assets/sticker_previews/hand_drawn/hand-drawn-01.png"
  },
  "mat-sticker-12ywne7": {
    "id": "mat-sticker-12ywne7",
    "title": "粉色蝴蝶结",
    "type": "sticker",
    "group": "hand-drawn",
    "status": "上架",
    "sortOrder": 23,
    "author": "小天使",
    "sourceKey": "sticker:hand-drawn:hand-drawn-02.png",
    "packId": "hand-drawn",
    "src": "./assets/user_stickers/hand-drawn-02.png",
    "previewSrc": "./assets/sticker_previews/hand_drawn/hand-drawn-02.png"
  },
  "mat-sticker-1seunmu": {
    "id": "mat-sticker-1seunmu",
    "title": "粉色箭头",
    "type": "sticker",
    "group": "hand-drawn",
    "status": "上架",
    "sortOrder": 24,
    "author": "小天使",
    "sourceKey": "sticker:hand-drawn:hand-drawn-03.png",
    "packId": "hand-drawn",
    "src": "./assets/user_stickers/hand-drawn-03.png",
    "previewSrc": "./assets/sticker_previews/hand_drawn/hand-drawn-03.png"
  },
  "mat-sticker-43x8zt": {
    "id": "mat-sticker-43x8zt",
    "title": "粉色绑带",
    "type": "sticker",
    "group": "hand-drawn",
    "status": "上架",
    "sortOrder": 25,
    "author": "小天使",
    "sourceKey": "sticker:hand-drawn:hand-drawn-04.png",
    "packId": "hand-drawn",
    "src": "./assets/user_stickers/hand-drawn-04.png",
    "previewSrc": "./assets/sticker_previews/hand_drawn/hand-drawn-04.png"
  },
  "mat-sticker-165g8ik": {
    "id": "mat-sticker-165g8ik",
    "title": "粉色爱心翅膀",
    "type": "sticker",
    "group": "hand-drawn",
    "status": "上架",
    "sortOrder": 26,
    "author": "小天使",
    "sourceKey": "sticker:hand-drawn:hand-drawn-05.png",
    "packId": "hand-drawn",
    "src": "./assets/user_stickers/hand-drawn-05.png",
    "previewSrc": "./assets/sticker_previews/hand_drawn/hand-drawn-05.png"
  },
  "mat-sticker-bsqw8u": {
    "id": "mat-sticker-bsqw8u",
    "title": "粉色发光爱心",
    "type": "sticker",
    "group": "hand-drawn",
    "status": "上架",
    "sortOrder": 27,
    "author": "小天使",
    "sourceKey": "sticker:hand-drawn:hand-drawn-06.png",
    "packId": "hand-drawn",
    "src": "./assets/user_stickers/hand-drawn-06.png",
    "previewSrc": "./assets/sticker_previews/hand_drawn/hand-drawn-06.png"
  },
  "mat-sticker-1r0a6ze": {
    "id": "mat-sticker-1r0a6ze",
    "title": "粉色双爱心",
    "type": "sticker",
    "group": "hand-drawn",
    "status": "上架",
    "sortOrder": 28,
    "author": "小天使",
    "sourceKey": "sticker:hand-drawn:hand-drawn-07.png",
    "packId": "hand-drawn",
    "src": "./assets/user_stickers/hand-drawn-07.png",
    "previewSrc": "./assets/sticker_previews/hand_drawn/hand-drawn-07.png"
  },
  "mat-sticker-1ayctfm": {
    "id": "mat-sticker-1ayctfm",
    "title": "粉色天使字",
    "type": "sticker",
    "group": "hand-drawn",
    "status": "上架",
    "sortOrder": 29,
    "author": "小天使",
    "sourceKey": "sticker:hand-drawn:hand-drawn-08.png",
    "packId": "hand-drawn",
    "src": "./assets/user_stickers/hand-drawn-08.png",
    "previewSrc": "./assets/sticker_previews/hand_drawn/hand-drawn-08.png"
  },
  "mat-sticker-1lxcp15": {
    "id": "mat-sticker-1lxcp15",
    "title": "粉色星星十字",
    "type": "sticker",
    "group": "hand-drawn",
    "status": "上架",
    "sortOrder": 30,
    "author": "小天使",
    "sourceKey": "sticker:hand-drawn:hand-drawn-09.png",
    "packId": "hand-drawn",
    "src": "./assets/user_stickers/hand-drawn-09.png",
    "previewSrc": "./assets/sticker_previews/hand_drawn/hand-drawn-09.png"
  },
  "mat-sticker-1ioslnl": {
    "id": "mat-sticker-1ioslnl",
    "title": "粉色スキ",
    "type": "sticker",
    "group": "hand-drawn",
    "status": "上架",
    "sortOrder": 31,
    "author": "小天使",
    "sourceKey": "sticker:hand-drawn:hand-drawn-10.png",
    "packId": "hand-drawn",
    "src": "./assets/user_stickers/hand-drawn-10.png",
    "previewSrc": "./assets/sticker_previews/hand_drawn/hand-drawn-10.png"
  },
  "mat-frame-3bi9a": {
    "id": "mat-frame-3bi9a",
    "title": "竖版拍立得",
    "type": "frame",
    "group": "frame",
    "status": "上架",
    "sortOrder": 32,
    "author": "小天使",
    "sourceKey": "frame:portrait-clean",
    "src": "./assets/polaroid_frames/portrait-clean.png",
    "previewSrc": "./assets/polaroid_frame_previews/portrait-clean.png",
    "renderMode": "frame"
  },
  "mat-frame-lcevv1": {
    "id": "mat-frame-lcevv1",
    "title": "横版拍立得",
    "type": "frame",
    "group": "frame",
    "status": "上架",
    "sortOrder": 33,
    "author": "小天使",
    "sourceKey": "frame:landscape-clean",
    "src": "./assets/polaroid_frames/landscape-clean.png",
    "previewSrc": "./assets/polaroid_frame_previews/landscape-clean.png",
    "renderMode": "frame"
  },
  "mat-frame-1unh9n2": {
    "id": "mat-frame-1unh9n2",
    "title": "1:1 蕾丝星星",
    "type": "frame",
    "group": "overlay",
    "status": "上架",
    "sortOrder": 34,
    "author": "小天使",
    "sourceKey": "frame:texture-band-square",
    "src": "./assets/polaroid_frames/texture-band-square.png",
    "previewSrc": "./assets/polaroid_frame_previews/texture-band-square.png",
    "renderMode": "texture"
  },
  "mat-frame-1fasg1o": {
    "id": "mat-frame-1fasg1o",
    "title": "竖版4:3 蕾丝星星",
    "type": "frame",
    "group": "overlay",
    "status": "上架",
    "sortOrder": 35,
    "author": "小天使",
    "sourceKey": "frame:texture-band-vertical",
    "src": "./assets/polaroid_frames/texture-band-vertical.png",
    "previewSrc": "./assets/polaroid_frame_previews/texture-band-vertical.png",
    "renderMode": "texture"
  },
  "mat-frame-mfgnvt": {
    "id": "mat-frame-mfgnvt",
    "title": "1:1 蕾丝爱心",
    "type": "frame",
    "group": "overlay",
    "status": "上架",
    "sortOrder": 36,
    "author": "小天使",
    "sourceKey": "frame:texture-glow-square",
    "src": "./assets/polaroid_frames/texture-glow-square.png",
    "previewSrc": "./assets/polaroid_frame_previews/texture-glow-square.png",
    "renderMode": "texture"
  },
  "mat-frame-h2tkqg": {
    "id": "mat-frame-h2tkqg",
    "title": "竖版4:3 蕾丝爱心",
    "type": "frame",
    "group": "overlay",
    "status": "上架",
    "sortOrder": 37,
    "author": "小天使",
    "sourceKey": "frame:texture-glow-vertical",
    "src": "./assets/polaroid_frames/texture-glow-vertical.png",
    "previewSrc": "./assets/polaroid_frame_previews/texture-glow-vertical.png",
    "renderMode": "texture"
  },
  "mat-frame-1fe15ox": {
    "id": "mat-frame-1fe15ox",
    "title": "1:1 韩系波点",
    "type": "frame",
    "group": "overlay",
    "status": "上架",
    "sortOrder": 38,
    "author": "小天使",
    "sourceKey": "frame:texture-charm-square",
    "src": "./assets/polaroid_frames/texture-charm-square.png",
    "previewSrc": "./assets/polaroid_frame_previews/texture-charm-square.png",
    "renderMode": "texture"
  },
  "mat-frame-173cixb": {
    "id": "mat-frame-173cixb",
    "title": "竖版4:3 韩系波点",
    "type": "frame",
    "group": "overlay",
    "status": "上架",
    "sortOrder": 39,
    "author": "小天使",
    "sourceKey": "frame:texture-charm-vertical",
    "src": "./assets/polaroid_frames/texture-charm-vertical.png",
    "previewSrc": "./assets/polaroid_frame_previews/texture-charm-vertical.png",
    "renderMode": "texture"
  },
  "mat-text-hj4l6h": {
    "id": "mat-text-hj4l6h",
    "title": "今日の私、満点！",
    "type": "text",
    "group": "copy",
    "status": "上架",
    "sortOrder": 40,
    "author": "小天使",
    "sourceKey": "text:preset-copy-1",
    "content": "今日の私、満点！",
    "style": {}
  },
  "mat-text-vl753i": {
    "id": "mat-text-vl753i",
    "title": "自分が一番かわいいかも！",
    "type": "text",
    "group": "copy",
    "status": "上架",
    "sortOrder": 41,
    "author": "小天使",
    "sourceKey": "text:preset-copy-2",
    "content": "自分が一番かわいいかも！",
    "style": {}
  },
  "mat-text-j7gm1p": {
    "id": "mat-text-j7gm1p",
    "title": "世界一かわいい～",
    "type": "text",
    "group": "copy",
    "status": "上架",
    "sortOrder": 42,
    "author": "小天使",
    "sourceKey": "text:preset-copy-3",
    "content": "世界一かわいい～",
    "style": {}
  },
  "mat-text-gs6ms6": {
    "id": "mat-text-gs6ms6",
    "title": "天才的にかわいい！",
    "type": "text",
    "group": "copy",
    "status": "上架",
    "sortOrder": 43,
    "author": "小天使",
    "sourceKey": "text:preset-copy-4",
    "content": "天才的にかわいい！",
    "style": {}
  },
  "mat-text-oco6ew": {
    "id": "mat-text-oco6ew",
    "title": "かわいくてごめん～",
    "type": "text",
    "group": "copy",
    "status": "上架",
    "sortOrder": 44,
    "author": "小天使",
    "sourceKey": "text:preset-copy-5",
    "content": "かわいくてごめん～",
    "style": {}
  },
  "mat-text-1rrx9nm": {
    "id": "mat-text-1rrx9nm",
    "title": "推しは最高！",
    "type": "text",
    "group": "copy",
    "status": "上架",
    "sortOrder": 45,
    "author": "小天使",
    "sourceKey": "text:preset-copy-6",
    "content": "推しは最高！",
    "style": {}
  },
  "mat-text-wiy71r": {
    "id": "mat-text-wiy71r",
    "title": "推ししか勝たん！",
    "type": "text",
    "group": "copy",
    "status": "上架",
    "sortOrder": 46,
    "author": "小天使",
    "sourceKey": "text:preset-copy-7",
    "content": "推ししか勝たん！",
    "style": {}
  },
  "mat-text-1sivlny": {
    "id": "mat-text-1sivlny",
    "title": "推ししか見えない",
    "type": "text",
    "group": "copy",
    "status": "上架",
    "sortOrder": 47,
    "author": "小天使",
    "sourceKey": "text:preset-copy-8",
    "content": "推ししか見えない",
    "style": {}
  },
  "mat-text-neh0ik": {
    "id": "mat-text-neh0ik",
    "title": "推し依存症",
    "type": "text",
    "group": "copy",
    "status": "上架",
    "sortOrder": 48,
    "author": "小天使",
    "sourceKey": "text:preset-copy-9",
    "content": "推し依存症",
    "style": {}
  },
  "mat-text-13bi5a5": {
    "id": "mat-text-13bi5a5",
    "title": "ずっと応援してるよ",
    "type": "text",
    "group": "copy",
    "status": "上架",
    "sortOrder": 49,
    "author": "小天使",
    "sourceKey": "text:preset-copy-10",
    "content": "ずっと応援してるよ",
    "style": {}
  },
  "mat-text-1dnv8rw": {
    "id": "mat-text-1dnv8rw",
    "title": "推し大好きすぎる",
    "type": "text",
    "group": "copy",
    "status": "上架",
    "sortOrder": 50,
    "author": "小天使",
    "sourceKey": "text:preset-copy-11",
    "content": "推し大好きすぎる",
    "style": {}
  },
  "mat-text-10yp04w": {
    "id": "mat-text-10yp04w",
    "title": ">w<",
    "type": "text",
    "group": "kaomoji",
    "status": "上架",
    "sortOrder": 51,
    "author": "小天使",
    "content": ">w<",
    "style": {}
  },
  "mat-text-nbqdfs": {
    "id": "mat-text-nbqdfs",
    "title": "T_T",
    "type": "text",
    "group": "kaomoji",
    "status": "上架",
    "sortOrder": 52,
    "author": "小天使",
    "content": "T_T",
    "style": {}
  },
  "mat-text-xssw8j": {
    "id": "mat-text-xssw8j",
    "title": "( ᐡ. ̫ .ᐡ )",
    "type": "text",
    "group": "kaomoji",
    "status": "上架",
    "sortOrder": 53,
    "author": "小天使",
    "content": "( ᐡ. ̫ .ᐡ )",
    "style": {}
  },
  "mat-text-1xt72gm": {
    "id": "mat-text-1xt72gm",
    "title": "(՞ ܸ. .ܸ՞)",
    "type": "text",
    "group": "kaomoji",
    "status": "上架",
    "sortOrder": 54,
    "author": "小天使",
    "content": "(՞ ܸ. .ܸ՞)",
    "style": {}
  },
  "mat-text-rcx2ot": {
    "id": "mat-text-rcx2ot",
    "title": "♡⸜(˶˃ ᵕ ˂˶)⸝♡",
    "type": "text",
    "group": "kaomoji",
    "status": "上架",
    "sortOrder": 55,
    "author": "小天使",
    "content": "♡⸜(˶˃ ᵕ ˂˶)⸝♡",
    "style": {}
  },
  "mat-text-1s4yjuu": {
    "id": "mat-text-1s4yjuu",
    "title": "(っ ̫ -˘)",
    "type": "text",
    "group": "kaomoji",
    "status": "上架",
    "sortOrder": 56,
    "author": "小天使",
    "content": "(っ ̫ -˘)",
    "style": {}
  }
};
