// Generated from the Feishu Bitable material CMS.
// Do not edit by hand; run scripts/sync-material-cms.mjs.

export const MATERIAL_CMS_ITEMS = {
  "lab-face-cover-face-cover-lace-heart-png": {
    "id": "lab-face-cover-face-cover-lace-heart-png",
    "title": "猫嘴",
    "type": "sticker",
    "group": "face-cover",
    "status": "上架",
    "sortOrder": 1,
    "author": "小天使",
    "sourceKey": "sticker:user:face-cover-lace-heart.png",
    "packId": "face-cover",
    "src": "./assets/user_stickers/face-cover-lace-heart.png",
    "previewSrc": "./assets/sticker_previews/user/face-cover-lace-heart.png"
  },
  "lab-face-cover-sel_01-png": {
    "id": "lab-face-cover-sel_01-png",
    "title": "GAME OVER",
    "type": "sticker",
    "group": "face-cover",
    "status": "上架",
    "sortOrder": 2,
    "author": "小天使",
    "sourceKey": "sticker:user:sel_01.png",
    "packId": "face-cover",
    "src": "./assets/user_stickers/sel_01.png",
    "previewSrc": "./assets/sticker_previews/user/sel_01.png"
  },
  "lab-face-cover-sel_03-png": {
    "id": "lab-face-cover-sel_03-png",
    "title": "secret",
    "type": "sticker",
    "group": "face-cover",
    "status": "上架",
    "sortOrder": 3,
    "author": "小天使",
    "sourceKey": "sticker:user:sel_03.png",
    "packId": "face-cover",
    "src": "./assets/user_stickers/sel_03.png",
    "previewSrc": "./assets/sticker_previews/user/sel_03.png"
  },
  "mat-sticker-qd1dyv": {
    "id": "mat-sticker-qd1dyv",
    "title": "secret",
    "type": "sticker",
    "group": "face-cover",
    "status": "上架",
    "sortOrder": 4,
    "author": "小天使",
    "packId": "face-cover",
    "src": "./assets/user_stickers/split-11.png",
    "previewSrc": "./assets/sticker_previews/user/split-11.png"
  },
  "mat-sticker-x8gqke": {
    "id": "mat-sticker-x8gqke",
    "title": "secret",
    "type": "sticker",
    "group": "face-cover",
    "status": "上架",
    "sortOrder": 5,
    "author": "小天使",
    "packId": "face-cover",
    "src": "./assets/user_stickers/split-10.png",
    "previewSrc": "./assets/sticker_previews/user/split-10.png"
  },
  "mat-sticker-um0rkm": {
    "id": "mat-sticker-um0rkm",
    "title": "thank you",
    "type": "sticker",
    "group": "face-cover",
    "status": "上架",
    "sortOrder": 6,
    "author": "小天使",
    "packId": "face-cover",
    "src": "./assets/user_stickers/split-18.png",
    "previewSrc": "./assets/sticker_previews/user/split-18.png"
  },
  "mat-sticker-b8559p": {
    "id": "mat-sticker-b8559p",
    "title": "模糊爱心",
    "type": "sticker",
    "group": "face-cover",
    "status": "上架",
    "sortOrder": 7,
    "author": "小天使",
    "packId": "face-cover",
    "src": "./assets/user_stickers/split-19.png",
    "previewSrc": "./assets/sticker_previews/user/split-19.png"
  },
  "mat-sticker-n7nvpi": {
    "id": "mat-sticker-n7nvpi",
    "title": "みせないよ！",
    "type": "sticker",
    "group": "face-cover",
    "status": "上架",
    "sortOrder": 8,
    "author": "小天使",
    "packId": "face-cover",
    "src": "./assets/user_stickers/微信图片_20260702014117_517_13.png",
    "previewSrc": "./assets/sticker_previews/user/微信图片_20260702014117_517_13.png"
  },
  "mat-sticker-10pslce": {
    "id": "mat-sticker-10pslce",
    "title": "みせないよ！",
    "type": "sticker",
    "group": "face-cover",
    "status": "上架",
    "sortOrder": 9,
    "author": "小天使",
    "packId": "face-cover",
    "src": "./assets/user_stickers/微信图片_20260702014116_516_13.png",
    "previewSrc": "./assets/sticker_previews/user/微信图片_20260702014116_516_13.png"
  },
  "lab-face-cover-sel_08-png": {
    "id": "lab-face-cover-sel_08-png",
    "title": "きらい",
    "type": "sticker",
    "group": "face-cover",
    "status": "上架",
    "sortOrder": 10,
    "author": "小天使",
    "sourceKey": "sticker:user:sel_08.png",
    "packId": "face-cover",
    "src": "./assets/user_stickers/sel_08.png",
    "previewSrc": "./assets/sticker_previews/user/sel_08.png"
  },
  "lab-face-cover-sel_09-png": {
    "id": "lab-face-cover-sel_09-png",
    "title": "天使光环",
    "type": "sticker",
    "group": "face-cover",
    "status": "上架",
    "sortOrder": 11,
    "author": "小天使",
    "sourceKey": "sticker:user:sel_09.png",
    "packId": "face-cover",
    "src": "./assets/user_stickers/sel_09.png",
    "previewSrc": "./assets/sticker_previews/user/sel_09.png"
  },
  "lab-face-cover-sel_12-png": {
    "id": "lab-face-cover-sel_12-png",
    "title": "XXX",
    "type": "sticker",
    "group": "face-cover",
    "status": "上架",
    "sortOrder": 12,
    "author": "小天使",
    "sourceKey": "sticker:user:sel_12.png",
    "packId": "face-cover",
    "src": "./assets/user_stickers/sel_12.png",
    "previewSrc": "./assets/sticker_previews/user/sel_12.png"
  },
  "lab-face-cover-sel_13-png": {
    "id": "lab-face-cover-sel_13-png",
    "title": "爱心点赞",
    "type": "sticker",
    "group": "face-cover",
    "status": "上架",
    "sortOrder": 13,
    "author": "小天使",
    "sourceKey": "sticker:user:sel_13.png",
    "packId": "face-cover",
    "src": "./assets/user_stickers/sel_13.png",
    "previewSrc": "./assets/sticker_previews/user/sel_13.png"
  },
  "lab-face-cover-deco_02-png": {
    "id": "lab-face-cover-deco_02-png",
    "title": "みせないよ！",
    "type": "sticker",
    "group": "face-cover",
    "status": "上架",
    "sortOrder": 14,
    "author": "小天使",
    "sourceKey": "sticker:user:deco_02.png",
    "packId": "face-cover",
    "src": "./assets/user_stickers/deco_02.png",
    "previewSrc": "./assets/sticker_previews/user/deco_02.png"
  },
  "lab-face-cover-deco_08-png": {
    "id": "lab-face-cover-deco_08-png",
    "title": "爱心十字架",
    "type": "sticker",
    "group": "face-cover",
    "status": "上架",
    "sortOrder": 15,
    "author": "小天使",
    "sourceKey": "sticker:user:deco_08.png",
    "packId": "face-cover",
    "src": "./assets/user_stickers/deco_08.png",
    "previewSrc": "./assets/sticker_previews/user/deco_08.png"
  },
  "lab-face-cover-sel_05-png": {
    "id": "lab-face-cover-sel_05-png",
    "title": "すき气泡",
    "type": "sticker",
    "group": "face-cover",
    "status": "上架",
    "sortOrder": 16,
    "author": "小天使",
    "sourceKey": "sticker:user:sel_05.png",
    "packId": "face-cover",
    "src": "./assets/user_stickers/sel_05.png",
    "previewSrc": "./assets/sticker_previews/user/sel_05.png"
  },
  "lab-face-cover-sel_06-png": {
    "id": "lab-face-cover-sel_06-png",
    "title": "爱心气泡",
    "type": "sticker",
    "group": "face-cover",
    "status": "上架",
    "sortOrder": 17,
    "author": "小天使",
    "sourceKey": "sticker:user:sel_06.png",
    "packId": "face-cover",
    "src": "./assets/user_stickers/sel_06.png",
    "previewSrc": "./assets/sticker_previews/user/sel_06.png"
  },
  "lab-face-cover-sel_04-png": {
    "id": "lab-face-cover-sel_04-png",
    "title": "爱心死",
    "type": "sticker",
    "group": "face-cover",
    "status": "暂不上架",
    "sortOrder": 18,
    "author": "小天使",
    "sourceKey": "sticker:user:sel_04.png",
    "packId": "face-cover",
    "src": "./assets/user_stickers/sel_04.png",
    "previewSrc": "./assets/sticker_previews/user/sel_04.png"
  },
  "lab-face-cover-sel_07-png": {
    "id": "lab-face-cover-sel_07-png",
    "title": "が",
    "type": "sticker",
    "group": "face-cover",
    "status": "上架",
    "sortOrder": 19,
    "author": "小天使",
    "sourceKey": "sticker:user:sel_07.png",
    "packId": "face-cover",
    "src": "./assets/user_stickers/sel_07.png",
    "previewSrc": "./assets/sticker_previews/user/sel_07.png"
  },
  "lab-face-cover-sel_10-png": {
    "id": "lab-face-cover-sel_10-png",
    "title": "I HATE U",
    "type": "sticker",
    "group": "face-cover",
    "status": "上架",
    "sortOrder": 20,
    "author": "小天使",
    "sourceKey": "sticker:user:sel_10.png",
    "packId": "face-cover",
    "src": "./assets/user_stickers/sel_10.png",
    "previewSrc": "./assets/sticker_previews/user/sel_10.png"
  },
  "lab-face-cover-sel_11-png": {
    "id": "lab-face-cover-sel_11-png",
    "title": "secret",
    "type": "sticker",
    "group": "face-cover",
    "status": "上架",
    "sortOrder": 21,
    "author": "小天使",
    "sourceKey": "sticker:user:sel_11.png",
    "packId": "face-cover",
    "src": "./assets/user_stickers/sel_11.png",
    "previewSrc": "./assets/sticker_previews/user/sel_11.png"
  },
  "lab-face-cover-deco_01-png": {
    "id": "lab-face-cover-deco_01-png",
    "title": "みせないよ！",
    "type": "sticker",
    "group": "face-cover",
    "status": "上架",
    "sortOrder": 22,
    "author": "小天使",
    "sourceKey": "sticker:user:deco_01.png",
    "packId": "face-cover",
    "src": "./assets/user_stickers/deco_01.png",
    "previewSrc": "./assets/sticker_previews/user/deco_01.png"
  },
  "lab-face-cover-deco_03-png": {
    "id": "lab-face-cover-deco_03-png",
    "title": "爱心十字架",
    "type": "sticker",
    "group": "face-cover",
    "status": "上架",
    "sortOrder": 23,
    "author": "小天使",
    "sourceKey": "sticker:user:deco_03.png",
    "packId": "face-cover",
    "src": "./assets/user_stickers/deco_03.png",
    "previewSrc": "./assets/sticker_previews/user/deco_03.png"
  },
  "lab-face-cover-deco_04-png": {
    "id": "lab-face-cover-deco_04-png",
    "title": "爱心绑带",
    "type": "sticker",
    "group": "face-cover",
    "status": "上架",
    "sortOrder": 24,
    "author": "小天使",
    "sourceKey": "sticker:user:deco_04.png",
    "packId": "face-cover",
    "src": "./assets/user_stickers/deco_04.png",
    "previewSrc": "./assets/sticker_previews/user/deco_04.png"
  },
  "lab-face-cover-deco_05-png": {
    "id": "lab-face-cover-deco_05-png",
    "title": "爱心十字架",
    "type": "sticker",
    "group": "face-cover",
    "status": "上架",
    "sortOrder": 25,
    "author": "小天使",
    "sourceKey": "sticker:user:deco_05.png",
    "packId": "face-cover",
    "src": "./assets/user_stickers/deco_05.png",
    "previewSrc": "./assets/sticker_previews/user/deco_05.png"
  },
  "lab-face-cover-deco_06-png": {
    "id": "lab-face-cover-deco_06-png",
    "title": "爱心十字架",
    "type": "sticker",
    "group": "face-cover",
    "status": "上架",
    "sortOrder": 26,
    "author": "小天使",
    "sourceKey": "sticker:user:deco_06.png",
    "packId": "face-cover",
    "src": "./assets/user_stickers/deco_06.png",
    "previewSrc": "./assets/sticker_previews/user/deco_06.png"
  },
  "lab-face-cover-deco_07-png": {
    "id": "lab-face-cover-deco_07-png",
    "title": "爱心十字架",
    "type": "sticker",
    "group": "face-cover",
    "status": "上架",
    "sortOrder": 27,
    "author": "小天使",
    "sourceKey": "sticker:user:deco_07.png",
    "packId": "face-cover",
    "src": "./assets/user_stickers/deco_07.png",
    "previewSrc": "./assets/sticker_previews/user/deco_07.png"
  },
  "lab-pink-frame": {
    "id": "lab-pink-frame",
    "title": "粉色线框",
    "type": "sticker",
    "group": "hand-drawn",
    "status": "上架",
    "sortOrder": 28,
    "author": "小天使",
    "sourceKey": "sticker:hand-drawn:hand-drawn-01.png",
    "packId": "hand-drawn",
    "src": "./assets/user_stickers/hand-drawn-01.png",
    "previewSrc": "./assets/sticker_previews/hand_drawn/hand-drawn-01.png"
  },
  "lab-pink-ribbon": {
    "id": "lab-pink-ribbon",
    "title": "粉色蝴蝶结",
    "type": "sticker",
    "group": "hand-drawn",
    "status": "上架",
    "sortOrder": 29,
    "author": "小天使",
    "sourceKey": "sticker:hand-drawn:hand-drawn-02.png",
    "packId": "hand-drawn",
    "src": "./assets/user_stickers/hand-drawn-02.png",
    "previewSrc": "./assets/sticker_previews/hand_drawn/hand-drawn-02.png"
  },
  "lab-pink-arrow": {
    "id": "lab-pink-arrow",
    "title": "粉色箭头",
    "type": "sticker",
    "group": "hand-drawn",
    "status": "上架",
    "sortOrder": 30,
    "author": "小天使",
    "sourceKey": "sticker:hand-drawn:hand-drawn-03.png",
    "packId": "hand-drawn",
    "src": "./assets/user_stickers/hand-drawn-03.png",
    "previewSrc": "./assets/sticker_previews/hand_drawn/hand-drawn-03.png"
  },
  "lab-pink-bandage": {
    "id": "lab-pink-bandage",
    "title": "粉色绑带",
    "type": "sticker",
    "group": "hand-drawn",
    "status": "上架",
    "sortOrder": 31,
    "author": "小天使",
    "sourceKey": "sticker:hand-drawn:hand-drawn-04.png",
    "packId": "hand-drawn",
    "src": "./assets/user_stickers/hand-drawn-04.png",
    "previewSrc": "./assets/sticker_previews/hand_drawn/hand-drawn-04.png"
  },
  "lab-pink-heart-wings": {
    "id": "lab-pink-heart-wings",
    "title": "粉色爱心翅膀",
    "type": "sticker",
    "group": "hand-drawn",
    "status": "上架",
    "sortOrder": 32,
    "author": "小天使",
    "sourceKey": "sticker:hand-drawn:hand-drawn-05.png",
    "packId": "hand-drawn",
    "src": "./assets/user_stickers/hand-drawn-05.png",
    "previewSrc": "./assets/sticker_previews/hand_drawn/hand-drawn-05.png"
  },
  "lab-pink-glow-heart": {
    "id": "lab-pink-glow-heart",
    "title": "粉色发光爱心",
    "type": "sticker",
    "group": "hand-drawn",
    "status": "上架",
    "sortOrder": 33,
    "author": "小天使",
    "sourceKey": "sticker:hand-drawn:hand-drawn-06.png",
    "packId": "hand-drawn",
    "src": "./assets/user_stickers/hand-drawn-06.png",
    "previewSrc": "./assets/sticker_previews/hand_drawn/hand-drawn-06.png"
  },
  "lab-pink-double-heart": {
    "id": "lab-pink-double-heart",
    "title": "粉色双爱心",
    "type": "sticker",
    "group": "hand-drawn",
    "status": "上架",
    "sortOrder": 34,
    "author": "小天使",
    "sourceKey": "sticker:hand-drawn:hand-drawn-07.png",
    "packId": "hand-drawn",
    "src": "./assets/user_stickers/hand-drawn-07.png",
    "previewSrc": "./assets/sticker_previews/hand_drawn/hand-drawn-07.png"
  },
  "lab-pink-angel-text": {
    "id": "lab-pink-angel-text",
    "title": "粉色天使字",
    "type": "sticker",
    "group": "hand-drawn",
    "status": "上架",
    "sortOrder": 35,
    "author": "小天使",
    "sourceKey": "sticker:hand-drawn:hand-drawn-08.png",
    "packId": "hand-drawn",
    "src": "./assets/user_stickers/hand-drawn-08.png",
    "previewSrc": "./assets/sticker_previews/hand_drawn/hand-drawn-08.png"
  },
  "lab-pink-sparkle-cross": {
    "id": "lab-pink-sparkle-cross",
    "title": "粉色星星十字",
    "type": "sticker",
    "group": "hand-drawn",
    "status": "上架",
    "sortOrder": 36,
    "author": "小天使",
    "sourceKey": "sticker:hand-drawn:hand-drawn-09.png",
    "packId": "hand-drawn",
    "src": "./assets/user_stickers/hand-drawn-09.png",
    "previewSrc": "./assets/sticker_previews/hand_drawn/hand-drawn-09.png"
  },
  "lab-pink-suki": {
    "id": "lab-pink-suki",
    "title": "粉色スキ",
    "type": "sticker",
    "group": "hand-drawn",
    "status": "上架",
    "sortOrder": 37,
    "author": "小天使",
    "sourceKey": "sticker:hand-drawn:hand-drawn-10.png",
    "packId": "hand-drawn",
    "src": "./assets/user_stickers/hand-drawn-10.png",
    "previewSrc": "./assets/sticker_previews/hand_drawn/hand-drawn-10.png"
  },
  "lab-portrait-clean": {
    "id": "lab-portrait-clean",
    "title": "竖版拍立得",
    "type": "frame",
    "group": "frame",
    "status": "上架",
    "sortOrder": 38,
    "author": "小天使",
    "sourceKey": "frame:portrait-clean",
    "src": "./assets/polaroid_frames/portrait-clean.png",
    "previewSrc": "./assets/polaroid_frame_previews/portrait-clean.png",
    "renderMode": "frame"
  },
  "lab-landscape-clean": {
    "id": "lab-landscape-clean",
    "title": "横版拍立得",
    "type": "frame",
    "group": "frame",
    "status": "上架",
    "sortOrder": 39,
    "author": "小天使",
    "sourceKey": "frame:landscape-clean",
    "src": "./assets/polaroid_frames/landscape-clean.png",
    "previewSrc": "./assets/polaroid_frame_previews/landscape-clean.png",
    "renderMode": "frame"
  },
  "lab-texture-band-square": {
    "id": "lab-texture-band-square",
    "title": "1:1 蕾丝星星",
    "type": "frame",
    "group": "overlay",
    "status": "上架",
    "sortOrder": 40,
    "author": "小天使",
    "sourceKey": "frame:texture-band-square",
    "src": "./assets/polaroid_frames/texture-band-square.png",
    "previewSrc": "./assets/polaroid_frame_previews/texture-band-square.png",
    "renderMode": "texture"
  },
  "lab-texture-band-vertical": {
    "id": "lab-texture-band-vertical",
    "title": "竖版4:3 蕾丝星星",
    "type": "frame",
    "group": "overlay",
    "status": "上架",
    "sortOrder": 41,
    "author": "小天使",
    "sourceKey": "frame:texture-band-vertical",
    "src": "./assets/polaroid_frames/texture-band-vertical.png",
    "previewSrc": "./assets/polaroid_frame_previews/texture-band-vertical.png",
    "renderMode": "texture"
  },
  "lab-texture-glow-square": {
    "id": "lab-texture-glow-square",
    "title": "1:1 蕾丝爱心",
    "type": "frame",
    "group": "overlay",
    "status": "上架",
    "sortOrder": 42,
    "author": "小天使",
    "sourceKey": "frame:texture-glow-square",
    "src": "./assets/polaroid_frames/texture-glow-square.png",
    "previewSrc": "./assets/polaroid_frame_previews/texture-glow-square.png",
    "renderMode": "texture"
  },
  "lab-texture-glow-vertical": {
    "id": "lab-texture-glow-vertical",
    "title": "竖版4:3 蕾丝爱心",
    "type": "frame",
    "group": "overlay",
    "status": "上架",
    "sortOrder": 43,
    "author": "小天使",
    "sourceKey": "frame:texture-glow-vertical",
    "src": "./assets/polaroid_frames/texture-glow-vertical.png",
    "previewSrc": "./assets/polaroid_frame_previews/texture-glow-vertical.png",
    "renderMode": "texture"
  },
  "lab-texture-charm-square": {
    "id": "lab-texture-charm-square",
    "title": "1:1 韩系波点",
    "type": "frame",
    "group": "overlay",
    "status": "上架",
    "sortOrder": 44,
    "author": "小天使",
    "sourceKey": "frame:texture-charm-square",
    "src": "./assets/polaroid_frames/texture-charm-square.png",
    "previewSrc": "./assets/polaroid_frame_previews/texture-charm-square.png",
    "renderMode": "texture"
  },
  "lab-texture-charm-vertical": {
    "id": "lab-texture-charm-vertical",
    "title": "竖版4:3 韩系波点",
    "type": "frame",
    "group": "overlay",
    "status": "上架",
    "sortOrder": 45,
    "author": "小天使",
    "sourceKey": "frame:texture-charm-vertical",
    "src": "./assets/polaroid_frames/texture-charm-vertical.png",
    "previewSrc": "./assets/polaroid_frame_previews/texture-charm-vertical.png",
    "renderMode": "texture"
  },
  "lab-preset-copy-1": {
    "id": "lab-preset-copy-1",
    "title": "今日の私、満点！",
    "type": "text",
    "group": "copy",
    "status": "上架",
    "sortOrder": 46,
    "author": "小天使",
    "sourceKey": "text:preset-copy-1",
    "content": "今日の私、満点！",
    "style": {}
  },
  "lab-preset-copy-2": {
    "id": "lab-preset-copy-2",
    "title": "自分が一番かわいいかも！",
    "type": "text",
    "group": "copy",
    "status": "上架",
    "sortOrder": 47,
    "author": "小天使",
    "sourceKey": "text:preset-copy-2",
    "content": "自分が一番かわいいかも！",
    "style": {}
  },
  "lab-preset-copy-3": {
    "id": "lab-preset-copy-3",
    "title": "世界一かわいい～",
    "type": "text",
    "group": "copy",
    "status": "上架",
    "sortOrder": 48,
    "author": "小天使",
    "sourceKey": "text:preset-copy-3",
    "content": "世界一かわいい～",
    "style": {}
  },
  "lab-preset-copy-4": {
    "id": "lab-preset-copy-4",
    "title": "天才的にかわいい！",
    "type": "text",
    "group": "copy",
    "status": "上架",
    "sortOrder": 49,
    "author": "小天使",
    "sourceKey": "text:preset-copy-4",
    "content": "天才的にかわいい！",
    "style": {}
  },
  "lab-preset-copy-5": {
    "id": "lab-preset-copy-5",
    "title": "かわいくてごめん～",
    "type": "text",
    "group": "copy",
    "status": "上架",
    "sortOrder": 50,
    "author": "小天使",
    "sourceKey": "text:preset-copy-5",
    "content": "かわいくてごめん～",
    "style": {}
  },
  "lab-preset-copy-6": {
    "id": "lab-preset-copy-6",
    "title": "推しは最高！",
    "type": "text",
    "group": "copy",
    "status": "上架",
    "sortOrder": 51,
    "author": "小天使",
    "sourceKey": "text:preset-copy-6",
    "content": "推しは最高！",
    "style": {}
  },
  "lab-preset-copy-7": {
    "id": "lab-preset-copy-7",
    "title": "推ししか勝たん！",
    "type": "text",
    "group": "copy",
    "status": "上架",
    "sortOrder": 52,
    "author": "小天使",
    "sourceKey": "text:preset-copy-7",
    "content": "推ししか勝たん！",
    "style": {}
  },
  "lab-preset-copy-8": {
    "id": "lab-preset-copy-8",
    "title": "推ししか見えない",
    "type": "text",
    "group": "copy",
    "status": "上架",
    "sortOrder": 53,
    "author": "小天使",
    "sourceKey": "text:preset-copy-8",
    "content": "推ししか見えない",
    "style": {}
  },
  "lab-preset-copy-9": {
    "id": "lab-preset-copy-9",
    "title": "推し依存症",
    "type": "text",
    "group": "copy",
    "status": "上架",
    "sortOrder": 54,
    "author": "小天使",
    "sourceKey": "text:preset-copy-9",
    "content": "推し依存症",
    "style": {}
  },
  "lab-preset-copy-10": {
    "id": "lab-preset-copy-10",
    "title": "ずっと応援してるよ",
    "type": "text",
    "group": "copy",
    "status": "上架",
    "sortOrder": 55,
    "author": "小天使",
    "sourceKey": "text:preset-copy-10",
    "content": "ずっと応援してるよ",
    "style": {}
  },
  "lab-preset-copy-11": {
    "id": "lab-preset-copy-11",
    "title": "推し大好きすぎる",
    "type": "text",
    "group": "copy",
    "status": "上架",
    "sortOrder": 56,
    "author": "小天使",
    "sourceKey": "text:preset-copy-11",
    "content": "推し大好きすぎる",
    "style": {}
  },
  "lab-kaomoji-1": {
    "id": "lab-kaomoji-1",
    "title": ">w<",
    "type": "text",
    "group": "kaomoji",
    "status": "上架",
    "sortOrder": 57,
    "author": "小天使",
    "content": ">w<",
    "style": {}
  },
  "lab-kaomoji-2": {
    "id": "lab-kaomoji-2",
    "title": "T_T",
    "type": "text",
    "group": "kaomoji",
    "status": "上架",
    "sortOrder": 58,
    "author": "小天使",
    "content": "T_T",
    "style": {}
  },
  "lab-kaomoji-3": {
    "id": "lab-kaomoji-3",
    "title": "( ᐡ. ̫ .ᐡ )",
    "type": "text",
    "group": "kaomoji",
    "status": "上架",
    "sortOrder": 59,
    "author": "小天使",
    "content": "( ᐡ. ̫ .ᐡ )",
    "style": {}
  },
  "lab-kaomoji-4": {
    "id": "lab-kaomoji-4",
    "title": "(՞ ܸ. .ܸ՞)",
    "type": "text",
    "group": "kaomoji",
    "status": "上架",
    "sortOrder": 60,
    "author": "小天使",
    "content": "(՞ ܸ. .ܸ՞)",
    "style": {}
  },
  "lab-kaomoji-5": {
    "id": "lab-kaomoji-5",
    "title": "♡⸜(˶˃ ᵕ ˂˶)⸝♡",
    "type": "text",
    "group": "kaomoji",
    "status": "上架",
    "sortOrder": 61,
    "author": "小天使",
    "content": "♡⸜(˶˃ ᵕ ˂˶)⸝♡",
    "style": {}
  },
  "lab-kaomoji-6": {
    "id": "lab-kaomoji-6",
    "title": "(っ ̫ -˘)",
    "type": "text",
    "group": "kaomoji",
    "status": "上架",
    "sortOrder": 62,
    "author": "小天使",
    "content": "(っ ̫ -˘)",
    "style": {}
  }
};
